/** Real BridalLive export — source: items.xls at repo root */
import type { InventoryItem } from '../types/inventory'

/** Regenerate: npm run mock-catalog:import */
export const MOCK_CATALOG_ITEMS: InventoryItem[] = [
  {
    id: 'bl-49154',
    itemNumber: '49154',
    style: '4554',
    vendor: 'PRIVRA1',
    saleSearchQuery: '49154',
    department: 'Dress',
    size: '0',
    color: 'Ivery/Gold',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49153',
    itemNumber: '49153',
    style: 'CB91978J',
    vendor: 'CB91',
    saleSearchQuery: '49153',
    department: 'Dress',
    size: '0',
    color: 'Royal',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49152',
    itemNumber: '49152',
    style: '11211',
    vendor: 'FAV1',
    saleSearchQuery: '49152',
    department: 'Dress',
    size: '6',
    color: 'Red',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49151',
    itemNumber: '49151',
    style: 'COLOR18172DR',
    vendor: 'COLOR1',
    saleSearchQuery: '49151',
    department: 'Dress',
    size: '14',
    color: 'Silver',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49150',
    itemNumber: '49150',
    style: '57684',
    vendor: 'SH1',
    saleSearchQuery: '49150',
    department: 'Dress',
    size: '00',
    color: 'Nude/Silver',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49149',
    itemNumber: '49149',
    style: 'CB91C5847',
    vendor: 'CB91',
    saleSearchQuery: '49149',
    department: 'Dress',
    size: '12',
    color: 'Lt. Lavender',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49148',
    itemNumber: '49148',
    style: 'CB3812-96455DC',
    vendor: 'CB381',
    saleSearchQuery: '49148',
    department: 'Dress',
    size: 'L',
    color: 'Ivvery/Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49147',
    itemNumber: '49147',
    style: 'CB3812-96455DC',
    vendor: 'CB381',
    saleSearchQuery: '49147',
    department: 'Dress',
    size: 'M',
    color: 'Ivvery/Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49146',
    itemNumber: '49146',
    style: 'CB3812-96455DC',
    vendor: 'CB381',
    saleSearchQuery: '49146',
    department: 'Dress',
    size: 'S',
    color: 'Ivvery/Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49145',
    itemNumber: '49145',
    style: 'CB3812-96455DC',
    vendor: 'CB381',
    saleSearchQuery: '49145',
    department: 'Dress',
    size: 'XS',
    color: 'Ivvery/Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49144',
    itemNumber: '49144',
    style: 'CB38187803DC',
    vendor: 'CB381',
    saleSearchQuery: '49144',
    department: 'Dress',
    size: 'L',
    color: 'Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49143',
    itemNumber: '49143',
    style: 'CB38187803DC',
    vendor: 'CB381',
    saleSearchQuery: '49143',
    department: 'Dress',
    size: 'M',
    color: 'Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49142',
    itemNumber: '49142',
    style: 'CB38187803DC',
    vendor: 'CB381',
    saleSearchQuery: '49142',
    department: 'Dress',
    size: 'S',
    color: 'Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49141',
    itemNumber: '49141',
    style: 'CB38187803DC',
    vendor: 'CB381',
    saleSearchQuery: '49141',
    department: 'Dress',
    size: 'XS',
    color: 'Pink',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49140',
    itemNumber: '49140',
    style: 'CB38180655DC',
    vendor: 'CB381',
    saleSearchQuery: '49140',
    department: 'Dress',
    size: 'XS',
    color: 'HUnter/Nude',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49139',
    itemNumber: '49139',
    style: 'CB38180655DC',
    vendor: 'CB381',
    saleSearchQuery: '49139',
    department: 'Dress',
    size: 'XS',
    color: 'Navy/nude',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49138',
    itemNumber: '49138',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49138',
    department: 'Dress',
    size: 'L',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49137',
    itemNumber: '49137',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49137',
    department: 'Dress',
    size: 'M',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49136',
    itemNumber: '49136',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49136',
    department: 'Dress',
    size: 'S',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49135',
    itemNumber: '49135',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49135',
    department: 'Dress',
    size: 'XS',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49134',
    itemNumber: '49134',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49134',
    department: 'Dress',
    size: 'L',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49133',
    itemNumber: '49133',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49133',
    department: 'Dress',
    size: 'M',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49132',
    itemNumber: '49132',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49132',
    department: 'Dress',
    size: 'S',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49131',
    itemNumber: '49131',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49131',
    department: 'Dress',
    size: 'XS',
    color: 'Fuchsia',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49130',
    itemNumber: '49130',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49130',
    department: 'Dress',
    size: 'M',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49129',
    itemNumber: '49129',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49129',
    department: 'Dress',
    size: 'M',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49128',
    itemNumber: '49128',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49128',
    department: 'Dress',
    size: 'XS',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49127',
    itemNumber: '49127',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49127',
    department: 'Dress',
    size: 'S',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49126',
    itemNumber: '49126',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49126',
    department: 'Dress',
    size: 'M',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49125',
    itemNumber: '49125',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49125',
    department: 'Dress',
    size: 'L',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49124',
    itemNumber: '49124',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49124',
    department: 'Dress',
    size: 'L',
    color: 'AquA',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49123',
    itemNumber: '49123',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49123',
    department: 'Dress',
    size: 'M',
    color: 'AquA',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49122',
    itemNumber: '49122',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49122',
    department: 'Dress',
    size: 'S',
    color: 'AquA',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49121',
    itemNumber: '49121',
    style: 'CB3811-05903DC',
    vendor: 'CB381',
    saleSearchQuery: '49121',
    department: 'Dress',
    size: 'XS',
    color: 'AquA',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49120',
    itemNumber: '49120',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49120',
    department: 'Dress',
    size: 'M',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 3,
  },
  {
    id: 'bl-49119',
    itemNumber: '49119',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49119',
    department: 'Dress',
    size: 'S',
    color: 'Navy',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 3,
  },
  {
    id: 'bl-49118',
    itemNumber: '49118',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49118',
    department: 'Dress',
    size: 'M',
    color: 'Navy',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 3,
  },
  {
    id: 'bl-49117',
    itemNumber: '49117',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49117',
    department: 'Dress',
    size: 'L',
    color: 'Navy',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49116',
    itemNumber: '49116',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49116',
    department: 'Dress',
    size: 'XS',
    color: 'Navy',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49115',
    itemNumber: '49115',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49115',
    department: 'Dress',
    size: 'S',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49114',
    itemNumber: '49114',
    style: 'CB38138803DC',
    vendor: 'CB381',
    saleSearchQuery: '49114',
    department: 'Dress',
    size: 'XS',
    color: 'Purple',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49113',
    itemNumber: '49113',
    style: 'CB38107455DC',
    vendor: 'CB381',
    saleSearchQuery: '49113',
    department: 'Dress',
    size: 'L',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49112',
    itemNumber: '49112',
    style: 'CB38107455DC',
    vendor: 'CB381',
    saleSearchQuery: '49112',
    department: 'Dress',
    size: 'M',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49111',
    itemNumber: '49111',
    style: 'CB38107455DC',
    vendor: 'CB381',
    saleSearchQuery: '49111',
    department: 'Dress',
    size: 'S',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49110',
    itemNumber: '49110',
    style: 'CB38107455DC',
    vendor: 'CB381',
    saleSearchQuery: '49110',
    department: 'Dress',
    size: 'XS',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49109',
    itemNumber: '49109',
    style: 'CB38147655DC',
    vendor: 'CB381',
    saleSearchQuery: '49109',
    department: 'Dress',
    size: 'XS',
    color: 'Navy/Lavender',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49108',
    itemNumber: '49108',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49108',
    department: 'Dress',
    size: 'L',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49107',
    itemNumber: '49107',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49107',
    department: 'Dress',
    size: 'XS',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49106',
    itemNumber: '49106',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49106',
    department: 'Dress',
    size: 'S',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49105',
    itemNumber: '49105',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49105',
    department: 'Dress',
    size: 'L',
    color: 'Nude',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49104',
    itemNumber: '49104',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49104',
    department: 'Dress',
    size: 'XS',
    color: 'Nude',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49103',
    itemNumber: '49103',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49103',
    department: 'Dress',
    size: 'XS',
    color: 'Nude',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49102',
    itemNumber: '49102',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49102',
    department: 'Dress',
    size: 'S',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49101',
    itemNumber: '49101',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49101',
    department: 'Dress',
    size: 'M',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49100',
    itemNumber: '49100',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49100',
    department: 'Dress',
    size: 'M',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49099',
    itemNumber: '49099',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49099',
    department: 'Dress',
    size: 'S',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49098',
    itemNumber: '49098',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49098',
    department: 'Dress',
    size: 'Xs',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49097',
    itemNumber: '49097',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49097',
    department: 'Dress',
    size: 'M',
    color: 'Champaign',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49096',
    itemNumber: '49096',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49096',
    department: 'Dress',
    size: 'S',
    color: 'Champaign',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49095',
    itemNumber: '49095',
    style: 'CB38173503DC',
    vendor: 'CB381',
    saleSearchQuery: '49095',
    department: 'Dress',
    size: 'XS',
    color: 'Champaign',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49094',
    itemNumber: '49094',
    style: 'cd30909',
    vendor: 'CB381',
    saleSearchQuery: '49094',
    department: 'Dress',
    size: 'L',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49093',
    itemNumber: '49093',
    style: 'cd30909',
    vendor: 'CB381',
    saleSearchQuery: '49093',
    department: 'Dress',
    size: 'M',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49092',
    itemNumber: '49092',
    style: 'cd30909',
    vendor: 'CB381',
    saleSearchQuery: '49092',
    department: 'Dress',
    size: 'S',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49091',
    itemNumber: '49091',
    style: 'cd30909',
    vendor: 'CB381',
    saleSearchQuery: '49091',
    department: 'Dress',
    size: 'XS',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49090',
    itemNumber: '49090',
    style: 'CB38108355DC',
    vendor: 'CB381',
    saleSearchQuery: '49090',
    department: 'Dress',
    size: 'L',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49089',
    itemNumber: '49089',
    style: 'CB38108355DC',
    vendor: 'CB381',
    saleSearchQuery: '49089',
    department: 'Dress',
    size: 'M',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49088',
    itemNumber: '49088',
    style: 'CB38108355DC',
    vendor: 'CB381',
    saleSearchQuery: '49088',
    department: 'Dress',
    size: 'S',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49087',
    itemNumber: '49087',
    style: 'CB38108355DC',
    vendor: 'CB381',
    saleSearchQuery: '49087',
    department: 'Dress',
    size: 'XS',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49086',
    itemNumber: '49086',
    style: 'CB38178803DC',
    vendor: 'CB381',
    saleSearchQuery: '49086',
    department: 'Dress',
    size: 'S',
    color: 'Navy',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49085',
    itemNumber: '49085',
    style: '11402',
    vendor: 'FAV1',
    saleSearchQuery: '49085',
    department: 'Dress',
    size: '8',
    color: 'Lt Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49084',
    itemNumber: '49084',
    style: '11402',
    vendor: 'FAV1',
    saleSearchQuery: '49084',
    department: 'Dress',
    size: '8',
    color: 'Lt Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: -1,
  },
  {
    id: 'bl-49083',
    itemNumber: '49083',
    style: '4080013',
    vendor: 'ACC1',
    saleSearchQuery: '49083',
    department: 'Dress',
    size: '20',
    color: 'Blush',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49082',
    itemNumber: '49082',
    style: 'CB121A3233',
    vendor: 'CB121',
    saleSearchQuery: '49082',
    department: 'Dress',
    size: 'S',
    color: 'White',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49081',
    itemNumber: '49081',
    style: '4527',
    vendor: 'PRIVRA1',
    saleSearchQuery: '49081',
    department: 'Dress',
    size: '000',
    color: 'Ivery/Gold',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49080',
    itemNumber: '49080',
    style: '11255',
    vendor: 'FAV1',
    saleSearchQuery: '49080',
    department: 'Dress',
    size: '00',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: -1,
  },
  {
    id: 'bl-49079',
    itemNumber: '49079',
    style: '88330',
    vendor: 'AMR1',
    saleSearchQuery: '49079',
    department: 'Dress',
    size: '2',
    color: 'Perrywinkle',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49078',
    itemNumber: '49078',
    style: 'CB91792DC',
    vendor: 'CB91',
    saleSearchQuery: '49078',
    department: 'Dress',
    size: '16',
    color: 'Red',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49077',
    itemNumber: '49077',
    style: 'CB91227DC',
    vendor: 'CB91',
    saleSearchQuery: '49077',
    department: 'Dress',
    size: '2',
    color: 'Gold',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49076',
    itemNumber: '49076',
    style: 'CB91227DC',
    vendor: 'CB91',
    saleSearchQuery: '49076',
    department: 'Dress',
    size: '4',
    color: 'Gold',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49075',
    itemNumber: '49075',
    style: 'CB91227DC',
    vendor: 'CB91',
    saleSearchQuery: '49075',
    department: 'Dress',
    size: '12',
    color: 'Lavender',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49074',
    itemNumber: '49074',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49074',
    department: 'Dress',
    size: '10',
    color: 'Gold',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49073',
    itemNumber: '49073',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49073',
    department: 'Dress',
    size: '8',
    color: 'Gold',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49072',
    itemNumber: '49072',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49072',
    department: 'Dress',
    size: '8',
    color: 'Black',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49071',
    itemNumber: '49071',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49071',
    department: 'Dress',
    size: '16',
    color: 'Red',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49070',
    itemNumber: '49070',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49070',
    department: 'Dress',
    size: '2',
    color: 'Red',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49069',
    itemNumber: '49069',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49069',
    department: 'Dress',
    size: '10',
    color: 'Red',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49068',
    itemNumber: '49068',
    style: 'CB91727DC',
    vendor: 'CB91',
    saleSearchQuery: '49068',
    department: 'Dress',
    size: '6',
    color: 'Red',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49067',
    itemNumber: '49067',
    style: '57684',
    vendor: 'SH1',
    saleSearchQuery: '49067',
    department: 'Dress',
    size: '4',
    color: 'Royal',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49066',
    itemNumber: '49066',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49066',
    department: 'Dress',
    size: 'L',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49065',
    itemNumber: '49065',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49065',
    department: 'Dress',
    size: 'M',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49064',
    itemNumber: '49064',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49064',
    department: 'Dress',
    size: 'XS',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49063',
    itemNumber: '49063',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49063',
    department: 'Dress',
    size: 'S',
    color: 'Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
  {
    id: 'bl-49062',
    itemNumber: '49062',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49062',
    department: 'Dress',
    size: 'S',
    color: 'Denim',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49061',
    itemNumber: '49061',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49061',
    department: 'Dress',
    size: 'XS',
    color: 'Denim',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49060',
    itemNumber: '49060',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49060',
    department: 'Dress',
    size: 'M',
    color: 'Denim',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49059',
    itemNumber: '49059',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49059',
    department: 'Dress',
    size: 'L',
    color: 'Denim',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49058',
    itemNumber: '49058',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49058',
    department: 'Dress',
    size: 'L',
    color: 'Denim Blue',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 0,
  },
  {
    id: 'bl-49057',
    itemNumber: '49057',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49057',
    department: 'Dress',
    size: 'L',
    color: 'Lylac',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49056',
    itemNumber: '49056',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49056',
    department: 'Dress',
    size: 'M',
    color: 'Lylac',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 1,
  },
  {
    id: 'bl-49055',
    itemNumber: '49055',
    style: 'CD55830',
    vendor: 'CB381',
    saleSearchQuery: '49055',
    department: 'Dress',
    size: 'S',
    color: 'Lylac',
    locationId: 'store-1',
    locationName: 'Main Boutique',
    onHand: 2,
  },
]
